#
# Release setting
#
export CONFIG_FLOATING_RELEASE
export CONFIG_PLATFORM_LE
export CONFIG_USE_SHARE_MEM

export CONFIG_LITE-FESP_FOR_LINUX
export CONFIG_LITE-FESP_FOR_LINUX_64
export CONFIG_LITE-FESP_FOR_HIFI3
export CONFIG_LITE-FESP_FOR_HIFI4
export CONFIG_LITE-FESP_FOR_VIVO-M4F
export CONFIG_LITE-FESP_FOR_MSTAR8339
export CONFIG_LITE-FESP_FOR_MSTAR848_M4
export CONFIG_LITE-FESP_FOR_HIMIX3518
export CONFIG_LITE-FESP_FOR_LITEOS_HISIV500
export CONFIG_LITE-FESP_FOR_XR872-M4F
export CONFIG_LITE-FESP_FOR_LINUX_HI3556
export CONFIG_LITE-FESP_FOR_LINUX_HI3516E
export CONFIG_LITE-FESP_FOR_MTK2712_64
export CONFIG_LITE-FESP_FOR_ANDOID_ARM_R11
export CONFIG_LITE-FESP_FOR_ANDROID_AARCH64_R11
export CONFIG_LITE-FESP_FOR_ANDOID_ARM_R14
export CONFIG_LITE-FESP_FOR_ANDROID_AARCH64_R14
export CONFIG_LITE-FESP_FOR_BES2300
export CONFIG_LITE-FESP_FOR_RK3308_32
export CONFIG_LITE-FESP_FOR_RK3308_64
export CONFIG_LITE-FESP_FOR_MT8516_64
export CONFIG_LITE-FESP_FOR_Allwinner_R16

export CONFIG_LITE-FESPD_MOBILE
export CONFIG_LITE-FESPD_HEADSET
export CONFIG_LITE-FESPD_HOME
export CONFIG_LITE-FESPD-AEC
export CONFIG_RDMA_FFT_512
export CONFIG_RDMA_FFT_256
export CONFIG_FFT_256

export CONFIG_LITE-FESPD_FREQOUT_DIRECT

export CONFIG_GSC_HALF_VAD

export CONFIG_WAKEUP_NCHANNEL
export CONFIG_WAKEUP_USE_VAD
export CONFIG_WAKEUP_DICT_PHONEME
export CONFIG_WAKEUP_DICT_CHAR
export CONFIG_WAKEUP_DICT_WORD
export CONFIG_WAKEUP_NN_DNN
export CONFIG_WAKEUP_NN_FSMN
export CONFIG_WAKEUP_FBANK_CHANS24
export CONFIG_WAKEUP_FBANK_CHANS40
export CONFIG_WAKEUP_HAMMING400
export CONFIG_WAKEUP_HAMMING480
export CONFIG_WAKEUP_HANNING512
export CONFIG_WAKEUP_XCHECK
export CONFIG_WAKEUP_XTERM
export CONFIG_WAKEUP_DELAY
export CONFIG_WAKEUP_DUR_PENALTY
export CONFIG_WAKEUP_DUMP_SCORE
export CONFIG_WAKEUP_RESET

export CONFIG_SEVC_NN_GRU
export CONFIG_SEVC_NN_FSMN
export CONFIG_SEVC_PHONE
export CONFIG_SEVC_CAR
export CONFIG_SEVC_MULTI_CORE

export CONFIG_LITE-WAKEUP
export CONFIG_LITE-UDA
export CONFIG_LITE-SEVC
export CONFIG_FAR_FIELD_COMMUNICATION
#
# Release float or fixed version
#
# lite-fespd-aec: support fixed version only
# lite-fespd:     support fixed version only
# lite-wakeup:    support fixed version only
# lite-uda:       support both fixed & float version
#
CONFIG_FLOATING_RELEASE=n

#
# Release little or big endian
#
CONFIG_PLATFORM_LE=y



#
# Shared mem
#
CONFIG_USE_SHARE_MEM=y

#
# Release for different platforms
#
#CONFIG_LITE-FESP_FOR_LINUX=y
CONFIG_LITE-FESP_FOR_LINUX_64=y
#CONFIG_LITE-FESP_FOR_HIFI3=y
#CONFIG_LITE-FESP_FOR_HIFI4=y
#CONFIG_LITE-FESP_FOR_VIVO-M4F=y
#CONFIG_LITE-FESP_FOR_MSTAR8339=y
#CONFIG_LITE-FESP_FOR_MSTAR848_M4=y
#CONFIG_LITE-FESP_FOR_HIMIX3518=y
#CONFIG_LITE-FESP_FOR_LITEOS_HISIV500=y
#CONFIG_LITE-FESP_FOR_XR872-M4F=y
#CONFIG_LITE-FESP_FOR_LINUX_HI3556=y
#CONFIG_LITE-FESP_FOR_LINUX_HI3516E=y
#CONFIG_LITE-FESP_FOR_RK3308_32=y
#CONFIG_LITE-FESP_FOR_RK3308_64=y
#CONFIG_LITE-FESP_FOR_Allwinner_R16=y
#CONFIG_LITE-FESP_FOR_MTK2712_64=y
#CONFIG_LITE-FESP_FOR_ANDROID_ARM_R11=y
#CONFIG_LITE-FESP_FOR_ANDROID_AARCH64_R11=y
#CONFIG_LITE-FESP_FOR_ANDROID_ARM_R14=y
#CONFIG_LITE-FESP_FOR_ANDROID_AARCH64_R14=y
# CONFIG_LITE-FESP_FOR_BES2300=y

#
# Release for different scenes about uda
#
CONFIG_LITE-FESPD_MOBILE=y
#CONFIG_LITE-FESPD_HEADSET=y
#CONFIG_LITE-FESPD_HOME=y

#
# Select fft length
#
# Attention:
#     1.Mobile:  support 512-point fft only
#     2.Home:    support 512-point fft only
#     3.Headset: support 512-point fft only
CONFIG_RDMA_FFT_512=y
# CONFIG_RDMA_FFT_256=y
# CONFIG_FFT_256=y

#
# Uda configuration
#
# Attention:
#     1. FREQOUT_DIRECT is only valid on mobile scene;
#     2. HALF_VAD is only valid on mobile scene;
#
#CONFIG_LITE-FESPD_FREQOUT_DIRECT=y
CONFIG_GSC_HALF_VAD=y

#
# Wakeup configuration
#
## output frame scores for each word
#CONFIG_WAKEUP_DUMP_SCORE=y
## enable multi-channel wakeup support
CONFIG_WAKEUP_NCHANNEL=n
#CONFIG_WAKEUP_USE_VAD=y
CONFIG_WAKEUP_DICT_PHONEME=y
CONFIG_WAKEUP_DICT_CHAR=y
# enable end-to-end function
CONFIG_WAKEUP_DICT_WORD=y
#CONFIG_WAKEUP_NN_DNN=y
CONFIG_WAKEUP_NN_FSMN=y
CONFIG_WAKEUP_FBANK_CHANS24=y
CONFIG_WAKEUP_FBANK_CHANS40=y
CONFIG_WAKEUP_HAMMING400=y
CONFIG_WAKEUP_HAMMING480=y
#CONFIG_WAKEUP_HANNING512=y
CONFIG_WAKEUP_XCHECK=y
CONFIG_WAKEUP_XTERM=y
CONFIG_WAKEUP_DELAY=y
CONFIG_WAKEUP_DUR_PENALTY=y
CONFIG_WAKEUP_RESET=y


#
# Sevc configuration
#
#CONFIG_SEVC_NN_GRU=y
CONFIG_SEVC_NN_FSMN=y
#CONFIG_SEVC_CAR=y
CONFIG_SEVC_PHONE=y
#CONFIG_FAR_FIELD_COMMUNICATION=y
CONFIG_SEVC_MULTI_CORE=y

#
# FESPD with AEC switch
#
# Attention:
#     1.Mobile:  support aec
#     2.Home:    not support aec
#     3.Headset: not support aec
CONFIG_LITE-FESPD-AEC=n

#
# Lite-wakeup release
#
CONFIG_LITE-WAKEUP=n

#
# Lite-uda release
#
CONFIG_LITE-UDA=n

CONFIG_LITE-SEVC=y

