#
# config for specific functions
#

ifeq (${CONFIG_WAKEUP_NCHANNEL}, y)
CFLAGS += -DWAKEUP_NCHANNEL
endif

ifneq (${CONFIG_WAKEUP_USE_VAD}, y)
CFLAGS += -DWKP_VAD_DISABLE
endif

ifeq (${CONFIG_WAKEUP_DICT_PHONEME}, y)
CFLAGS += -DWAKEUP_DICT_PHONEME
endif

ifeq (${CONFIG_WAKEUP_DICT_CHAR}, y)
CFLAGS += -DWAKEUP_DICT_CHAR
endif

ifeq (${CONFIG_WAKEUP_DICT_WORD}, y)
CFLAGS += -DWAKEUP_DICT_WORD
endif

ifeq (${CONFIG_WAKEUP_NN_DNN}, y)
CFLAGS += -DWAKEUP_NN_DNN
endif

ifeq (${CONFIG_WAKEUP_NN_FSMN}, y)
CFLAGS += -DWAKEUP_NN_FSMN
endif

ifeq (${CONFIG_WAKEUP_FBANK_CHANS24}, y)
CFLAGS += -DWAKEUP_FBANK24
endif

ifeq (${CONFIG_WAKEUP_FBANK_CHANS40}, y)
CFLAGS += -DWAKEUP_FBANK40
endif

ifeq (${CONFIG_WAKEUP_FBANK_CHANS40}, y)
CFLAGS += -DWAKEUP_FBANK_CHANS_MAX=40
else
ifeq (${CONFIG_WAKEUP_FBANK_CHANS24}, y)
CFLAGS += -DWAKEUP_FBANK_CHANS_MAX=24
endif
endif

ifeq (${CONFIG_WAKEUP_HAMMING400}, y)
CFLAGS += -DWAKEUP_HAMMING400
endif

ifeq (${CONFIG_WAKEUP_HAMMING480}, y)
CFLAGS += -DWAKEUP_HAMMING480
endif

ifeq (${CONFIG_WAKEUP_HANNING512}, y)
CFLAGS += -DWAKEUP_HANNING512
endif

ifeq (${CONFIG_WAKEUP_XCHECK}, y)
CFLAGS += -DWAKEUP_XCHECK
endif

ifeq (${CONFIG_WAKEUP_XTERM}, y)
CFLAGS += -DWAKEUP_XTERM
endif

ifeq (${CONFIG_WAKEUP_DELAY}, y)
CFLAGS += -DWAKEUP_DELAY
endif

ifeq (${CONFIG_WAKEUP_DUR_PENALTY}, y)
CFLAGS += -DWAKEUP_DUR_PENALTY
endif

ifeq (${CONFIG_WAKEUP_RESET}, y)
CFLAGS += -DWAKEUP_RESET
endif

ifeq (${CONFIG_WAKEUP_DUMP_SCORE}, y)
CFLAGS += -DWAKEUP_DUMP_SCORE
endif

ifeq (${CONFIG_PLATFORM_LE}, y)
CFLAGS += -D__PLATFORM_LE__
endif
